### PR TITLE
OCPBUGS-21829: Merge upstream

### PR DESCRIPTION
**Pull request by pierreprinetti**
This is a manual merge of upstream/master that resolves conflicts in `go.mod`, `go.sum` and `vendor/modules.txt`.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
In general it LGTM, perhaps the deps failure could be fixed with `go mod tidy`?

**Comment by pierreprinetti** [comment]
> In general it LGTM, perhaps the deps failure could be fixed with `go mod tidy`?

Unfortunately not. The upstream go.mod lists some dependencies with version “v0.0.0”, and overrides them with real versions in a “replace” stanza. Unfortunately, the tool that is supposed to lint go.mod in that failing job is stricter than the Go toolchain and doesn’t seem to understand “replace”.

**Comment by pierreprinetti** [comment]
/hold
Wait for https://github.com/kubernetes-csi/csi-driver-nfs/pull/528

**Comment by pierreprinetti** [comment]
/hold cancel
Applied https://github.com/kubernetes-csi/csi-driver-nfs/pull/528 in the merge commit; the upstream patch should eventually merge gracefully.

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
