### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by mdbooth**
/kind cleanup

This is a merge of current upstream, which doesn't look like it has been done since June 2019! This change is impossibly large, but we are so far behind I don't any good solution other than to take it and resolve to never let this happen again.

I had to manually resolve merge conflicts with https://github.com/openshift/csi-driver-nfs/pull/31 so I'd be grateful if @jsafrane could look at it carefully, particularly `NodeUnpublishVolume` in `pkg/nfs/nodeserver.go`.

### CODE REVIEW

**Comment by mdbooth** [comment]
Need to fix the unit tests in relation to the changes in https://github.com/openshift/csi-driver-nfs/pull/31.

**Comment by jsafrane** [comment]
What is always useful is to provide a link with diff between upstream (usually tag, `master` in this case) and result of this pr:
https://github.com/kubernetes-csi/csi-driver-nfs/compare/master...mdbooth:upstream-merge

I can see that the diff contains only Dockerfile and OWNERS and #31, which is a good sign.

Nobody ever reviews these merges file by file...

**Comment by jsafrane** [comment]
Checked how #31 was ported
/lgtm
(but it needs serious testing...)

**Review by Fedosin — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
